apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dwgsn48m8-python 
  janus-idp.io/tekton: dwgsn48m8-python
  backstage.io/kubernetes-id: dwgsn48m8-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dwgsn48m8-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  